### ISSUE TITLE
当使用代理的时候无法获取IP，导致undefined crash

### ISSUE THREAD

**Issue by HellMagic** [song940/geoip-local#1]
本地开发环境下使用代理没有获取有效的local address 导致在index.js第9行没有对ip undefined做判断导致web server crash

**Comment by HellMagic** [comment]
诶，好像不对，我们使用的是1.0.5版本，为什么现在的package.json的version是1.0.3？是之后谁改动了么。。。index.js里面的内容几乎完全不一样了。。。

**Comment by HellMagic** [comment]
@song940 松哥，代码写的有点问题，if (!!ip || ip === '127.0.0.1' || ip.indexOf('192.168') > -1) 还是没有解决ip为undefined的问题－－你前面添加了!!ip但是后面使用的是“||”，当ip为undefined的时候还是会进行后面的匹配，所以到ip.indexOf还是有问题，把“||”换成“&&”OK。eg: if (!!ip && (ip === '127.0.0.1' || ip.indexOf('192.168') > -1))

**Comment by HellMagic** [comment]
@song940  我没办法reopen这个issues所以就在这里commented了，抽时间可以fix一下

**Comment by lsongdev** [comment]
@HellMagic fixed .
